# Generated by Django 3.2.9 on 2021-11-18 09:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend_userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fav_ticker',
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickers_text', models.CharField(max_length=10)),
                ('shares_holding', models.IntegerField(default=1)),
                ('bought_date', models.DateTimeField(default=datetime.datetime(2021, 11, 18, 9, 1, 40, 317332, tzinfo=utc), verbose_name='Date Bought')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
