# Generated by Django 3.2.9 on 2021-11-22 01:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend_userapp', '0002_auto_20211118_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='bought_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 1, 43, 58, 77185, tzinfo=utc), verbose_name='Date Bought'),
        ),
    ]
