# Generated by Django 3.2.9 on 2021-11-22 04:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend_userapp', '0003_alter_ticker_bought_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='bought_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 22, 4, 7, 16, 421140, tzinfo=utc), verbose_name='Date Bought'),
        ),
    ]
